ci:
    skip: ["mypy"]  # for some reason it can't find the settings

repos:
-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    -   id: black
        language_version: python3.10
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies:
            - "django-stubs"
            - "djangorestframework"
            - "djangorestframework-stubs"
            - "django-filter-stubs"
            - "django-phonenumber-field"
            - "phonenumberslite"
            - "django_extensions"
            - "drf-spectacular"
            - "django-filter"
            - "django-reversion"
        args:
            - --no-incremental
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.1.4'
    hooks:
    -   id: ruff
        name: ruff
        args:
        - --fix
exclude: api/migrations
