repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        language_version: python3.10
        args:
        - --diff
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort
        args:
        - --diff
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.254'
    hooks:
    -   id: ruff
        name: ruff
        args:
        - --diff
        - --fix
exclude: api/migrations
