services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"   
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-net

  redis:
    image: redis:latest
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"   
    volumes:
      - redis-data:/data
    networks:
      - shared-net

  celery_worker:
    build: .
    command: >
      sh -c "
        uv run celery -A django_webapps worker --loglevel=info
      "
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      REDIS_CACHE_DEFAULT: "redis://redis:6379/1"
      REDIS_CACHE_SELECT2: "redis://redis:6379/2"
    depends_on:
      - postgres
      - redis
    networks:
      - shared-net

  celery_beat:
    build: .
    command: >
      sh -c "
        uv run celery -A django_webapps beat --loglevel=info
      "
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      REDIS_CACHE_DEFAULT: "redis://redis:6379/1"
      REDIS_CACHE_SELECT2: "redis://redis:6379/2"
    depends_on:
      - postgres
      - redis
    networks:
      - shared-net

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/code/static:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shared-net

volumes:
  postgres-data:
  redis-data:

networks:
  shared-net:
    driver: bridge
