services:
  web:
    build: .
    command: >
      sh -c "
        uv run manage.py migrate &&
        uv run manage.py collectstatic --noinput &&
        uv run manage.py compilemessages &&
        uv run gunicorn django_webapps.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - .env
    volumes:
      - .:/code
      - static_volume:/code/static
    depends_on:
      - postgres
      - redis
    networks:
        - shared-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static
    restart: always
    depends_on:
      - web
    networks:
        - shared-net

  redis:
    image: redis:latest
    container_name: redis_broker
    restart: always
    volumes:
      - redis-data:/data
    networks:
        - shared-net

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
        - shared-net

  celery_worker:
    build: .
    command: >
      sh -c "
        uv run celery -A django_webapps worker --loglevel=info
      "
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - web
    networks:
        - shared-net

  celery_beat:
    build:  .
    command: >
      sh -c "
        uv run celery -A django_webapps beat --loglevel=info
      "
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - web
    networks:
        - shared-net

  bot:
    build: ../samanthas-telegram-bot
    command: >
      sh -c "
        uv run python bot/main.py
      "
    env_file:
      - ../samanthas-telegram-bot/.env
    volumes:
      - ../samanthas-telegram-bot:/bot
    depends_on:
      - redis
      - postgres
    networks:
      - shared-net
    profiles:
      - bot


volumes:
  redis-data:
  postgres-data:
  static_volume:


networks:
  shared-net:
    driver: bridge
