[tool.poetry]
name = "django-webapps"
version = "0.1.0"
description = ""
authors = ["Dmitry Kolomatskiy <58207913+lemontree210@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "django_webapps"}]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.6"
gunicorn = "^20.1.0"
django-phonenumber-field = {extras = ["phonenumberslite"], version = "^7.0.2"}
django-extensions = "^3.2.1"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
ruff = "^0.0.244"
pre-commit = "^3.0.4"
icecream = "^2.1.3"
isort = "^5.12.0"
graphviz = "^0.20.1"

[tool.black]
line-length = 99
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 99
skip_glob = ["api/migrations/*"]

[tool.ruff]
line-length = 99
exclude = ["api/migrations"]
per-file-ignores = {"__init__.py" = ["F401"]}

# Assume Python 3.10.
target-version = "py310"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
