[tool.black]
line-length = 99
target-version = ['py310']

[tool.django-stubs]
django_settings_module = "django_webapps.settings"

[tool.isort]
profile = "black"
line_length = 99
skip_glob = ["api/migrations/*"]

[tool.mypy]
exclude = "api/migrations"
ignore_missing_imports = true
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
python_version = "3.10"
strict = true
disallow_any_generics = false
disallow_untyped_calls = false
warn_return_any = false


[tool.poetry]
name = "django-webapps"
version = "0.1.0"
description = ""
authors = ["Dmitry Kolomatskiy <58207913+lemontree210@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "django_webapps"}]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.6"
gunicorn = "^20.1.0"
django-phonenumber-field = {extras = ["phonenumberslite"], version = "^7.0.2"}
django-extensions = "^3.2.1"
psycopg2-binary = "^2.9.5"
djangorestframework = "^3.14.0"
drf-spectacular = "^0.26.0"
django-filter = "^22.1"
django-filter-stubs = "^0.1.2"
djangorestframework-stubs = "^1.10.0"
django-stubs = "^1.16.0"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
ruff = "^0.0.257"
pre-commit = "^3.0.4"
icecream = "^2.1.3"
isort = "^5.12.0"
graphviz = "^0.20.1"
mypy = "^1.1.1"
django-stubs = "^1.16.0"
djangorestframework-stubs = "^1.10.0"

[tool.ruff]
line-length = 99
exclude = ["api/migrations"]
per-file-ignores = {"__init__.py" = ["F401"]}
# Pyflakes and pycodestyle Error (included by default without explicit "select"),
# I = isort, N = pep8-naming, PL = pylint, UP = pyupgrade
# A = flake8-builtins, DJ = flake8-django C4 = flake8-comprehensions, DTZ = flake8-datetimez,
# ISC = flake8-implicit-str-concat, T20 = flake8-print, RET = flake8-return, SIM = flake8-simplify,
# ARG = flake8-unused-arguments, PTH = flake8-use-pathlib
select = ["E", "F", "I", "N", "PL", "UP", "A", "DJ", "C4", "DTZ", "ISC", "T20", "RET", "SIM", "ARG", "PTH"]
# can add ERA (eradicate) later in here ^ for deleting commented out code
# Ignore: A003 (class attribute `id`/`type` is shadowing a python builtin) because class attributes don't really shadow Python builtins
ignore = ["A003"]

# Assume Python 3.10.
target-version = "py310"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[mypy.plugins.django-stubs]
django_settings_module = "api.settings"
