# Generated by Django 4.1.6 on 2023-02-22 16:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age_from", models.IntegerField()),
                ("age_to", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommunicationLanguageMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name_internal",
                    models.CharField(
                        help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name_en", models.CharField(max_length=255, unique=True)),
                ("name_ru", models.CharField(max_length=255, unique=True)),
                ("name_ua", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="approximate_date_of_birth",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="native_languages",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="tz_summer_relative_to_utc",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="tz_winter_relative_to_utc",
        ),
        migrations.RemoveField(
            model_name="student",
            name="requires_communication_in_ukrainian",
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="utc_timedelta",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="teacher",
            name="has_prior_teaching_experience",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="simultaneous_groups",
            field=models.IntegerField(
                default=1, help_text="Number of groups the teacher can teach simultaneously"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="weekly_frequency_per_group",
            field=models.IntegerField(
                default=1,
                help_text="Number of times per week the teacher can have classes with each group",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="information_source",
            field=models.TextField(
                verbose_name="how did they learn about Samantha Smith's Group?"
            ),
        ),
        migrations.DeleteModel(
            name="InformationSource",
        ),
        migrations.DeleteModel(
            name="NativeLanguage",
        ),
        migrations.AddField(
            model_name="group",
            name="communication_language_mode",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.communicationlanguagemode",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="communication_language_mode",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.communicationlanguagemode",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="age_range",
            field=models.ForeignKey(
                default=None,
                help_text="We do not ask students for their exact age. They choose an age range when registering with us.",
                on_delete=django.db.models.deletion.PROTECT,
                to="api.agerange",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="student_age_ranges",
            field=models.ManyToManyField(
                help_text="Age ranges of students that the teacher is willing to teach. The 'from's and 'to's of these ranges are wider than those the students choose for themselves.",
                to="api.agerange",
            ),
        ),
    ]
