# Generated by Django 4.1.6 on 2023-02-22 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_personalinfo_information_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="tz_summer_relative_to_utc",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="tz_winter_relative_to_utc",
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="utc_timedelta",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
