# Generated by Django 4.1.7 on 2023-03-02 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_agerange_communicationlanguagemode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agerange",
            name="name",
        ),
    ]
