# Generated by Django 4.1.6 on 2023-02-10 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_dayofweek_timeslot_person_date_and_time_added_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinatorStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("in_place_since", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnrollmentTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.teachinglanguage"
                    ),
                ),
                ("levels", models.ManyToManyField(to="api.languagelevel")),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentTestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "enrollment_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.enrollmenttest"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentTestQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.enrollmenttestquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("in_place_since", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NativeLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("in_place_since", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeacherStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("in_place_since", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="group",
            name="availability_slot",
            field=models.ManyToManyField(to="api.dayandtimeslot"),
        ),
        migrations.AddField(
            model_name="group",
            name="is_for_staff_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_slots",
            field=models.ManyToManyField(to="api.dayandtimeslot"),
        ),
        migrations.AddField(
            model_name="person",
            name="chatwoot_conversation_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="registration_bot_chat_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TeacherLogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_log_from_self",
                        to="api.group",
                    ),
                ),
                (
                    "teacher_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="api.teacherinfo",
                    ),
                ),
                (
                    "to_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_log_to_self",
                        to="api.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentLogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_log_from_self",
                        to="api.group",
                    ),
                ),
                (
                    "student_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="api.studentinfo",
                    ),
                ),
                (
                    "to_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_log_to_self",
                        to="api.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupLogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.group"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnrollmentTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("answers", models.ManyToManyField(to="api.enrollmenttestquestionoption")),
                (
                    "student_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.studentinfo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoordinatorLogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "coordinator_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="api.coordinatorinfo",
                    ),
                ),
                (
                    "from_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinator_log_from_self",
                        to="api.group",
                    ),
                ),
                (
                    "to_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinator_log_to_self",
                        to="api.group",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coordinatorinfo",
            name="status",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.PROTECT, to="api.coordinatorstatus"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="status",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.PROTECT, to="api.groupstatus"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="native_language",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.PROTECT, to="api.nativelanguage"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentinfo",
            name="status",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.PROTECT, to="api.studentstatus"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="status",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.PROTECT, to="api.teacherstatus"
            ),
            preserve_default=False,
        ),
    ]
