# Generated by Django 4.1.7 on 2023-03-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_teacherunder18_alter_coordinatorstatus_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="communicationlanguagemode",
            name="fcommunicationlanguagemode_name_internal",
        ),
        migrations.RemoveConstraint(
            model_name="coordinatorlogeventname",
            name="fcoordinatorlogeventname_name",
        ),
        migrations.RemoveConstraint(
            model_name="grouplogeventname",
            name="fgrouplogeventname_name",
        ),
        migrations.RemoveConstraint(
            model_name="studentlogeventname",
            name="fstudentlogeventname_name",
        ),
        migrations.RemoveConstraint(
            model_name="teacherlogeventname",
            name="fteacherlogeventname_name",
        ),
        migrations.RemoveConstraint(
            model_name="teachinglanguage",
            name="fteachinglanguage_name_internal",
        ),
        migrations.RemoveField(
            model_name="coordinatorlogeventname",
            name="name",
        ),
        migrations.RemoveField(
            model_name="coordinatorstatus",
            name="name",
        ),
        migrations.RemoveField(
            model_name="grouplogeventname",
            name="name",
        ),
        migrations.RemoveField(
            model_name="groupstatus",
            name="name",
        ),
        migrations.RemoveField(
            model_name="studentlogeventname",
            name="name",
        ),
        migrations.RemoveField(
            model_name="studentstatus",
            name="name",
        ),
        migrations.RemoveField(
            model_name="teacherlogeventname",
            name="name",
        ),
        migrations.RemoveField(
            model_name="teacherstatus",
            name="name",
        ),
        migrations.AddField(
            model_name="coordinatorlogeventname",
            name="name_for_user",
            field=models.CharField(
                default="", max_length=100, verbose_name="Readable name for coordinator"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coordinatorlogeventname",
            name="name_internal",
            field=models.CharField(
                default="",
                help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                max_length=50,
                unique=True,
                verbose_name="internal name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coordinatorstatus",
            name="name_for_user",
            field=models.CharField(
                default="", max_length=100, verbose_name="Readable name for coordinator"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coordinatorstatus",
            name="name_internal",
            field=models.CharField(
                default="",
                help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                max_length=50,
                unique=True,
                verbose_name="internal name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grouplogeventname",
            name="name_for_user",
            field=models.CharField(
                default="", max_length=100, verbose_name="Readable name for coordinator"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grouplogeventname",
            name="name_internal",
            field=models.CharField(
                default="",
                help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                max_length=50,
                unique=True,
                verbose_name="internal name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupstatus",
            name="name_for_user",
            field=models.CharField(
                default="", max_length=100, verbose_name="Readable name for coordinator"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupstatus",
            name="name_internal",
            field=models.CharField(
                default="",
                help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                max_length=50,
                unique=True,
                verbose_name="internal name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentlogeventname",
            name="name_for_user",
            field=models.CharField(
                default="", max_length=100, verbose_name="Readable name for coordinator"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentlogeventname",
            name="name_internal",
            field=models.CharField(
                default="",
                help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                max_length=50,
                unique=True,
                verbose_name="internal name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentstatus",
            name="name_for_user",
            field=models.CharField(
                default="", max_length=100, verbose_name="Readable name for coordinator"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentstatus",
            name="name_internal",
            field=models.CharField(
                default="",
                help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                max_length=50,
                unique=True,
                verbose_name="internal name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherlogeventname",
            name="name_for_user",
            field=models.CharField(
                default="", max_length=100, verbose_name="Readable name for coordinator"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherlogeventname",
            name="name_internal",
            field=models.CharField(
                default="",
                help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                max_length=50,
                unique=True,
                verbose_name="internal name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherstatus",
            name="name_for_user",
            field=models.CharField(
                default="", max_length=100, verbose_name="Readable name for coordinator"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherstatus",
            name="name_internal",
            field=models.CharField(
                default="",
                help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                max_length=50,
                unique=True,
                verbose_name="internal name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="communicationlanguagemode",
            name="name_en",
            field=models.CharField(max_length=255, unique=True, verbose_name="name in English"),
        ),
        migrations.AlterField(
            model_name="communicationlanguagemode",
            name="name_internal",
            field=models.CharField(
                help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                max_length=50,
                unique=True,
                verbose_name="internal name",
            ),
        ),
        migrations.AlterField(
            model_name="communicationlanguagemode",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True, verbose_name="name in Russian"),
        ),
        migrations.AlterField(
            model_name="communicationlanguagemode",
            name="name_ua",
            field=models.CharField(max_length=255, unique=True, verbose_name="name in Ukrainian"),
        ),
        migrations.AlterField(
            model_name="coordinator",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                help_text="mentor of this coordinator. One coordinator can have many interns",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interns",
                to="api.coordinator",
            ),
        ),
        migrations.AlterField(
            model_name="dayofweek",
            name="name_en",
            field=models.CharField(max_length=255, unique=True, verbose_name="name in English"),
        ),
        migrations.AlterField(
            model_name="dayofweek",
            name="name_internal",
            field=models.CharField(
                help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                max_length=50,
                unique=True,
                verbose_name="internal name",
            ),
        ),
        migrations.AlterField(
            model_name="dayofweek",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True, verbose_name="name in Russian"),
        ),
        migrations.AlterField(
            model_name="dayofweek",
            name="name_ua",
            field=models.CharField(max_length=255, unique=True, verbose_name="name in Ukrainian"),
        ),
        migrations.AlterField(
            model_name="teachinglanguage",
            name="name_en",
            field=models.CharField(max_length=255, unique=True, verbose_name="name in English"),
        ),
        migrations.AlterField(
            model_name="teachinglanguage",
            name="name_internal",
            field=models.CharField(
                help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                max_length=50,
                unique=True,
                verbose_name="internal name",
            ),
        ),
        migrations.AlterField(
            model_name="teachinglanguage",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True, verbose_name="name in Russian"),
        ),
        migrations.AlterField(
            model_name="teachinglanguage",
            name="name_ua",
            field=models.CharField(max_length=255, unique=True, verbose_name="name in Ukrainian"),
        ),
    ]
