# Generated by Django 4.1.6 on 2023-02-22 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_personalinfo_tz_summer_relative_to_utc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="approximate_date_of_birth",
        ),
    ]
