# Generated by Django 5.1.7 on 2025-06-09 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_coordinator_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinator",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Django user",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="legacy_gid",
            field=models.IntegerField(
                blank=True,
                help_text="Group id from the old database",
                null=True,
                verbose_name="legacy group id",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teaching_languages_and_levels",
            field=models.ManyToManyField(
                to="api.languageandlevel", verbose_name="Teaching languages and levels"
            ),
        ),
        migrations.AlterField(
            model_name="teacherunder18",
            name="teaching_languages_and_levels",
            field=models.ManyToManyField(
                to="api.languageandlevel", verbose_name="Teaching languages and levels"
            ),
        ),
    ]
