# Generated by Django 4.1.6 on 2023-02-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_coordinatorstatus_enrollmenttest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="friday",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="monday",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="saturday",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="sunday",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="thursday",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="tuesday",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="wednesday",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
