# Generated by Django 5.0.4 on 2024-04-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_fake_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinator",
            name="legacy_cid",
            field=models.IntegerField(help_text="Coordinator id from the old database", null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="legacy_gid",
            field=models.IntegerField(help_text="Group id from the old database", null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="legacy_sid",
            field=models.IntegerField(help_text="Student id from the old database", null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="legacy_tid",
            field=models.IntegerField(help_text="Teacher id from the old database", null=True),
        ),
    ]
