# Generated by Django 4.1.7 on 2023-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_coordinatorlogeventrule_coordinatorlogeventtype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayofweek",
            name="index",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
