# Generated by Django 4.1.7 on 2023-03-02 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_agerange_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="categories",
        ),
        migrations.DeleteModel(
            name="TeacherCategory",
        ),
    ]
