# Generated by Django 4.1.7 on 2023-03-08 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_enrollmenttestquestionoption_only_one_correct_option_per_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="lesson_duration",
            new_name="lesson_duration_in_minutes",
        ),
    ]
