# Generated by Django 4.1.7 on 2023-03-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0004_remove_communicationlanguagemode_fcommunicationlanguagemode_name_internal_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="communicationlanguagemode",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="fcommunicationlanguagemode_name_internal"
            ),
        ),
        migrations.AddConstraint(
            model_name="coordinatorlogeventname",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="fcoordinatorlogeventname_name_internal"
            ),
        ),
        migrations.AddConstraint(
            model_name="grouplogeventname",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="fgrouplogeventname_name_internal"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentlogeventname",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="fstudentlogeventname_name_internal"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherlogeventname",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="fteacherlogeventname_name_internal"
            ),
        ),
        migrations.AddConstraint(
            model_name="teachinglanguage",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="fteachinglanguage_name_internal"
            ),
        ),
    ]
