# Generated by Django 5.1.7 on 2025-04-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_coordinator_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinatorlogevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("applied", "Applied for the role"),
                    ("joined", "Joined the common group"),
                    (
                        "took_new_group",
                        "Took a new group (not transferred from another coordinator)",
                    ),
                    ("group_started_classes", "The group started classes"),
                    (
                        "requested_transfer",
                        "Requested that the group be transferred to a different coordinator",
                    ),
                    (
                        "transfer_canceled",
                        "Transfer canceled (declined or the coordinator changed their mind)",
                    ),
                    ("transferred", "Transfer of group to another coordinator completed"),
                    ("took_transfer", "Received group from another coordinator"),
                    ("gone_on_leave", "Gone on leave"),
                    ("returned_from_leave", "Returned from leave"),
                    ("left_prematurely", "Left the project prematurely"),
                    (
                        "finished_and_leaving",
                        "Finished working and announced that they are leaving the project",
                    ),
                    (
                        "finished_and_staying",
                        "Finished working and announced that they are staying in the project",
                    ),
                    ("expelled", "Expelled from the project"),
                    ("access_revoked", "Access to corporate resources revoked"),
                    ("group_aborted", "Group finished prematurely"),
                    ("group_finished", "Group studies are finished"),
                    (
                        "added_student_to_existing group",
                        "Added student to a group that was already studying",
                    ),
                ],
                max_length=50,
                verbose_name="event type",
            ),
        ),
    ]
