# Generated by Django 4.1.6 on 2023-02-10 18:14
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_group_friday_group_monday_group_saturday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinatorstatus",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dayofweek",
            name="index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dayofweek",
            name="name_en",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dayofweek",
            name="name_ru",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dayofweek",
            name="name_ua",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollmenttestquestion",
            name="text",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollmenttestquestionoption",
            name="is_correct",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollmenttestquestionoption",
            name="text",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="is_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="group",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="telegram_chat_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grouplogitem",
            name="type",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupstatus",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="languagelevel",
            name="rank",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nativelanguage",
            name="name_en",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nativelanguage",
            name="name_ru",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nativelanguage",
            name="name_ua",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="approximate_date_of_birth",
            field=models.DateField(default=datetime(year=1970, month=1, day=1).date),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="tg_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="tz_summer_relative_to_utc",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="tz_winter_relative_to_utc",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentinfo",
            name="is_member_of_speaking_club",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentinfo",
            name="requires_communication_in_ukrainian",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentinfo",
            name="requires_help_with_CV",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentstatus",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherstatus",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teachinglanguage",
            name="name_en",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teachinglanguage",
            name="name_ru",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teachinglanguage",
            name="name_ua",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeslot",
            name="from_utc_hour",
            field=models.TimeField(default=datetime(year=1, month=1, day=1).time),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeslot",
            name="to_utc_hour",
            field=models.TimeField(default=datetime(year=1, month=1, day=1).time),
            preserve_default=False,
        ),
    ]
