# Generated by Django 5.1.7 on 2025-06-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_coordinator_user_alter_group_legacy_gid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="legacy_sid",
            field=models.IntegerField(
                blank=True,
                help_text="Student id from the old database",
                null=True,
                verbose_name="legacy student id",
            ),
        ),
    ]
