# Generated by Django 4.1.6 on 2023-02-11 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_coordinatorstatus_name_dayofweek_index_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dayofweek",
            name="index",
        ),
    ]
