# Generated by Django 4.1.7 on 2023-03-08 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_lesson_duration_group_lesson_duration_in_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
