# Generated by Django 4.1.7 on 2023-03-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_dayofweek_options_alter_personalinfo_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coordinatorstatus",
            name="in_place_since",
        ),
        migrations.RemoveField(
            model_name="groupstatus",
            name="in_place_since",
        ),
        migrations.RemoveField(
            model_name="studentstatus",
            name="in_place_since",
        ),
        migrations.RemoveField(
            model_name="teacherstatus",
            name="in_place_since",
        ),
        migrations.AddField(
            model_name="coordinatorstatus",
            name="since",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="groupstatus",
            name="since",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="studentstatus",
            name="since",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="teacherstatus",
            name="since",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
