# Generated by Django 5.1.7 on 2025-04-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_student_project_status_and_more"),
        ("api", "0005_alter_coordinatorlogevent_type"),
    ]

    operations = []
