# Generated by Django 5.1.7 on 2025-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_student_legacy_sid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="legacy_tid",
            field=models.IntegerField(
                blank=True,
                help_text="Teacher id from the old database",
                null=True,
                verbose_name="legacy teacher id",
            ),
        ),
    ]
