# Generated by Django 4.1.7 on 2023-03-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0005_communicationlanguagemode_fcommunicationlanguagemode_name_internal_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="language_and_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.teachinglanguageandlevel"
            ),
        ),
        migrations.CreateModel(
            name="SpeakingClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("telegram_chat_url", models.URLField(blank=True, null=True)),
                (
                    "is_for_children",
                    models.BooleanField(
                        default=False, verbose_name="Is this a speaking club for children?"
                    ),
                ),
                ("coordinators", models.ManyToManyField(to="api.coordinator")),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.teachinglanguage"
                    ),
                ),
                ("students", models.ManyToManyField(to="api.student")),
                ("teachers", models.ManyToManyField(to="api.teacher")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
