# Generated by Django 4.1.7 on 2023-03-05 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_dayofweek_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dayandtimeslot",
            options={"ordering": ("day_of_week__index", "time_slot__from_utc_hour")},
        ),
    ]
