# Generated by Django 5.1.7 on 2025-06-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_teacher_legacy_tid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinator",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("pending", "Completed registration, but not in working status yet"),
                    ("working_below_threshold", "Координирует, минимум групп не набран (5)"),
                    ("working_ok", "Working, required amount of groups reached"),
                    ("working_limit_reached", "Координирует, минимум групп набран (20)"),
                    ("on_leave", "On leave"),
                    ("left_prematurely", "Announced that they cannot participate in the project"),
                    ("finished_stays", "Finished coordinating but remains in the project"),
                    ("finished_left", "Finished coordinating and left the project"),
                    ("removed", "All access revoked, accounts closed"),
                    ("banned", "Banned from the project"),
                ],
                help_text="Status of this coordinator with regard to project as a whole",
                max_length=50,
                verbose_name="Status in project",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="situational_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "attention",
                        "Some sort of problem: needs substitute teacher, change of coordinator etc.",
                    ),
                    ("holiday", "Holiday"),
                ],
                max_length=50,
                verbose_name="situational status",
            ),
        ),
    ]
