# Generated by Django 4.1.7 on 2023-03-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_dayandtimeslot_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="status_since",
            field=models.DateTimeField(),
        ),
    ]
