# Generated by Django 4.1.7 on 2023-03-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_coordinatorstatus_in_place_since_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coordinatorstatus",
            name="since",
        ),
        migrations.RemoveField(
            model_name="groupstatus",
            name="since",
        ),
        migrations.RemoveField(
            model_name="studentstatus",
            name="since",
        ),
        migrations.RemoveField(
            model_name="teacherstatus",
            name="since",
        ),
        migrations.AddField(
            model_name="group",
            name="status_since",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="status_since",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="coordinatorstatus",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="groupstatus",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studentstatus",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="teacherstatus",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="CoordinatorStatusName",
        ),
        migrations.DeleteModel(
            name="GroupStatusName",
        ),
        migrations.DeleteModel(
            name="StudentStatusName",
        ),
        migrations.DeleteModel(
            name="TeacherStatusName",
        ),
    ]
