# Generated by Django 4.1.7 on 2023-03-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_group_language_and_level_speakingclub"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoordinatorLogEventName",
            new_name="CoordinatorLogEventType",
        ),
        migrations.RenameModel(
            old_name="GroupLogEventName",
            new_name="GroupLogEventType",
        ),
        migrations.RenameModel(
            old_name="StudentLogEventName",
            new_name="StudentLogEventType",
        ),
        migrations.RenameModel(
            old_name="TeacherLogEventName",
            new_name="TeacherLogEventType",
        ),
        migrations.RemoveConstraint(
            model_name="coordinatorlogeventtype",
            name="fcoordinatorlogeventname_name_internal",
        ),
        migrations.RemoveConstraint(
            model_name="grouplogeventtype",
            name="fgrouplogeventname_name_internal",
        ),
        migrations.RemoveConstraint(
            model_name="studentlogeventtype",
            name="fstudentlogeventname_name_internal",
        ),
        migrations.RemoveConstraint(
            model_name="teacherlogeventtype",
            name="fteacherlogeventname_name_internal",
        ),
        migrations.RenameField(
            model_name="coordinatorlogevent",
            old_name="name",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="grouplogevent",
            old_name="name",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="studentlogevent",
            old_name="name",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="teacherlogevent",
            old_name="name",
            new_name="type",
        ),
        migrations.AddConstraint(
            model_name="coordinatorlogeventtype",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="fcoordinatorlogeventtype_name_internal"
            ),
        ),
        migrations.AddConstraint(
            model_name="grouplogeventtype",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="fgrouplogeventtype_name_internal"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentlogeventtype",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="fstudentlogeventtype_name_internal"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherlogeventtype",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="fteacherlogeventtype_name_internal"
            ),
        ),
    ]
