# Generated by Django 4.1.7 on 2023-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_personalinfo_uuid_alter_personalinfo_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dayandtimeslot",
            name="day_and_slot",
        ),
        migrations.AddConstraint(
            model_name="dayandtimeslot",
            constraint=models.UniqueConstraint(
                fields=("day_of_week_index", "time_slot"), name="unique_day_and_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("monday__isnull", False),
                    ("tuesday__isnull", False),
                    ("wednesday__isnull", False),
                    ("thursday__isnull", False),
                    ("friday__isnull", False),
                    ("saturday__isnull", False),
                    ("sunday__isnull", False),
                    _connector="OR",
                ),
                name="at_least_one_day_time_slot_must_be_selected",
            ),
        ),
    ]
