# Generated by Django 4.1.6 on 2023-02-22 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_personalinfo_native_languages_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="requires_communication_in_ukrainian",
        ),
    ]
