# Generated by Django 4.1.6 on 2023-02-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_student_requires_communication_in_ukrainian"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="has_prior_teaching_experience",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="simultaneous_groups",
            field=models.IntegerField(
                default=1, help_text="Number of groups the teacher can teach simultaneously"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="weekly_frequency_per_group",
            field=models.IntegerField(
                default=1,
                help_text="Number of times per week the teacher can have classes with each group",
            ),
            preserve_default=False,
        ),
    ]
