# Generated by Django 4.1.7 on 2023-03-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_dayandtimeslot_day_and_slot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmenttest",
            name="age_ranges",
            field=models.ManyToManyField(blank=True, null=True, to="api.agerange"),
        ),
    ]
