# Generated by Django 4.1.7 on 2023-03-02 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_coordinatorstatus_since_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coordinatorstatus",
            options={"verbose_name_plural": "possible coordinator statuses"},
        ),
        migrations.AlterModelOptions(
            name="groupstatus",
            options={"verbose_name_plural": "possible group statuses"},
        ),
        migrations.AlterModelOptions(
            name="studentstatus",
            options={"verbose_name_plural": "possible student statuses"},
        ),
        migrations.AlterModelOptions(
            name="teacherstatus",
            options={"verbose_name_plural": "possible teacher statuses"},
        ),
        migrations.AlterField(
            model_name="coordinator",
            name="personal_info",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="as_%(class)s",
                serialize=False,
                to="api.personalinfo",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="personal_info",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="as_%(class)s",
                serialize=False,
                to="api.personalinfo",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="personal_info",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="as_%(class)s",
                serialize=False,
                to="api.personalinfo",
            ),
        ),
    ]
