# Generated by Django 5.1.7 on 2025-06-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_coordinator_project_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="availability_slots",
            field=models.ManyToManyField(
                blank=True, to="api.dayandtimeslot", verbose_name="availability slots"
            ),
        ),
    ]
