# Generated by Django 4.1.7 on 2023-03-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_group_status_since"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollmenttest",
            name="language",
        ),
        migrations.RemoveField(
            model_name="enrollmenttest",
            name="levels",
        ),
        migrations.AddField(
            model_name="enrollmenttest",
            name="languages_and_levels",
            field=models.ManyToManyField(to="api.teachinglanguageandlevel"),
        ),
        migrations.AlterField(
            model_name="teachinglanguageandlevel",
            name="level",
            field=models.CharField(
                choices=[
                    ("A0", "A0 (Starter)"),
                    ("A1", "A1 (Beginner)"),
                    ("A2", "A2 (Pre-Intermediate)"),
                    ("B1", "B1 (Intermediate)"),
                    ("B2", "B2 (Upper-Intermediate)"),
                    ("C1", "C1 (Advanced)"),
                ],
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="LanguageLevel",
        ),
    ]
