# Generated by Django 4.1.7 on 2023-03-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_enrollmenttest_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coordinator",
            name="status_since",
        ),
        migrations.RemoveField(
            model_name="student",
            name="status_since",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="status_since",
        ),
        migrations.RemoveField(
            model_name="teacherunder18",
            name="status_since",
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="information_source",
            field=models.TextField(
                help_text="how did they learn about Samantha Smith's Group?",
                verbose_name="source of info about SSG",
            ),
        ),
    ]
