# Generated by Django 5.1.7 on 2025-06-23 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_student_availability_slots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinator",
            name="status_since",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="date and time of last change of project-level or situational status",
                verbose_name="status since",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="information_source",
            field=models.TextField(
                blank=True,
                help_text="How did they learn about Samantha Smith's Group?",
                verbose_name="Source of information about SSG",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="status_since",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="date and time of last change of project-level or situational status",
                verbose_name="status since",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="status_since",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="date and time of last change of project-level or situational status",
                verbose_name="status since",
            ),
        ),
        migrations.AlterField(
            model_name="teacherunder18",
            name="status_since",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="date and time of last change of project-level or situational status",
                verbose_name="status since",
            ),
        ),
    ]
