# Generated by Django 4.1.7 on 2023-03-08 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_enrollmenttest_age_ranges"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name_internal",
                    models.CharField(
                        help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                        max_length=50,
                        unique=True,
                        verbose_name="internal name",
                    ),
                ),
                (
                    "name_for_user",
                    models.CharField(max_length=100, verbose_name="Readable name for coordinator"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="enrollmenttest",
            name="languages_and_levels",
        ),
        migrations.AddField(
            model_name="enrollmenttest",
            name="language",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="api.language"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enrollmenttest",
            name="age_ranges",
            field=models.ManyToManyField(
                blank=True,
                help_text="age ranges for which this test was designed. Leave blank for the test to be shown to candidates at all ages.",
                to="api.agerange",
            ),
        ),
        migrations.AddConstraint(
            model_name="languagelevel",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="flanguagelevel_name_internal"
            ),
        ),
        migrations.AddField(
            model_name="enrollmenttest",
            name="levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="level(s) of the language this test was designed for. Leave blank for the test to be shown for all levels.",
                to="api.languagelevel",
            ),
        ),
        migrations.AlterField(
            model_name="languageandlevel",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.languagelevel"
            ),
        ),
    ]
