# Generated by Django 4.1.7 on 2023-03-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_coordinatorstatus_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="status_since",
        ),
        migrations.AddField(
            model_name="coordinator",
            name="status_since",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="student",
            name="status_since",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="status_since",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
