# Generated by Django 4.1.6 on 2023-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_teacher_has_prior_teaching_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="student_age_ranges",
            field=models.ManyToManyField(
                help_text="Age ranges of students that the teacher is willing to teach. The 'from's and 'to's of these ranges are wider than those the students choose for themselves.",
                to="api.agerange",
            ),
        ),
    ]
