# Generated by Django 4.1.7 on 2023-03-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_personalinfo_status_since_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="availability_slots",
        ),
        migrations.AddField(
            model_name="student",
            name="availability_slots",
            field=models.ManyToManyField(to="api.dayandtimeslot"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="availability_slots",
            field=models.ManyToManyField(to="api.dayandtimeslot"),
        ),
    ]
