# Generated by Django 4.1.7 on 2023-03-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_languagelevel_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="agerange",
            name="age_from_to",
        ),
        migrations.AddField(
            model_name="agerange",
            name="type",
            field=models.CharField(
                choices=[
                    ("student", "for students to select their age"),
                    ("teacher", "for teacher to select desired ages of students"),
                    ("matching", "for matching algorithm"),
                ],
                default=None,
                help_text="who/what is this range designed for",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enrollmenttest",
            name="age_ranges",
            field=models.ManyToManyField(
                blank=True,
                help_text="age ranges for which this test was designed. Leave blank for the test to be shown to all ages.",
                to="api.agerange",
            ),
        ),
        migrations.AddConstraint(
            model_name="agerange",
            constraint=models.UniqueConstraint(
                fields=("age_from", "age_to", "type"), name="unique_age_and_type"
            ),
        ),
    ]
