# Generated by Django 4.1.7 on 2023-03-07 10:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_coordinator_status_since_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
