# Generated by Django 4.1.6 on 2023-02-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_coordinatorlogitemname_grouplogitemname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name_en", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("name_ua", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="categories",
            field=models.ManyToManyField(to="api.teachercategory"),
        ),
    ]
