# Generated by Django 5.1.7 on 2025-07-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_coordinator_status_since_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="name")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
            },
        ),
        migrations.AlterField(
            model_name="coordinator",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("pending", "Completed registration, but not in working status yet"),
                    ("working_below_threshold", "Координирует, минимум групп не набран (3)"),
                    ("working_ok", "Working, required amount of groups reached"),
                    ("working_limit_reached", "Координирует, минимум групп набран (10)"),
                    ("on_leave", "On leave"),
                    ("left_prematurely", "Announced that they cannot participate in the project"),
                    ("finished_stays", "Finished coordinating but remains in the project"),
                    ("finished_left", "Finished coordinating and left the project"),
                    ("removed", "All access revoked, accounts closed"),
                    ("banned", "Banned from the project"),
                ],
                help_text="Status of this coordinator with regard to project as a whole",
                max_length=50,
                verbose_name="Status in project",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="teachers", to="api.role", verbose_name="roles"
            ),
        ),
    ]
