# Generated by Django 4.1.6 on 2023-02-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_teacher_student_age_ranges"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationLanguageMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name_internal",
                    models.CharField(
                        help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name_en", models.CharField(max_length=255, unique=True)),
                ("name_ru", models.CharField(max_length=255, unique=True)),
                ("name_ua", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="communication_language_mode",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.communicationlanguagemode",
            ),
            preserve_default=False,
        ),
    ]
