# Generated by Django 4.1.7 on 2023-03-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_personalinfo_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dayandtimeslot",
            options={"ordering": ("day_of_week_index", "time_slot__from_utc_hour")},
        ),
        migrations.RemoveConstraint(
            model_name="dayandtimeslot",
            name="day_and_slot",
        ),
        migrations.RemoveField(
            model_name="dayandtimeslot",
            name="day_of_week",
        ),
        migrations.AddField(
            model_name="dayandtimeslot",
            name="day_of_week_index",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="dayandtimeslot",
            constraint=models.UniqueConstraint(
                fields=("day_of_week_index", "time_slot"), name="day_and_slot"
            ),
        ),
        migrations.DeleteModel(
            name="DayOfWeek",
        ),
    ]
