# Generated by Django 4.1.7 on 2023-03-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_remove_personalinfo_availability_slots_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="additional_skills_comment",
            field=models.CharField(
                blank=True,
                help_text="other ways in which the applicant could help, besides teaching or helping otherteachers with materials or feedback (comment)",
                max_length=255,
                null=True,
                verbose_name="Comment on additional skills besides teaching",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="can_check_syllabus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="can_consult_other_teachers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="can_give_feedback",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="can_help_with_children_group",
            field=models.BooleanField(
                default=False, verbose_name="can help with children's groups"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="can_help_with_cv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="can_help_with_materials",
            field=models.BooleanField(
                default=False, verbose_name="can help with teaching materials"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="can_help_with_speaking_club",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="can_invite_to_class",
            field=models.BooleanField(
                default=False, verbose_name="can invite other teachers to their class"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="can_work_in_tandem",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="has_prior_teaching_experience",
            field=models.BooleanField(
                default=False,
                help_text="Has the applicant already worked as a teacher before applying at Samantha Smith's Group?",
            ),
        ),
    ]
