# Generated by Django 5.1.7 on 2025-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_role_alter_coordinator_project_status_teacher_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinator",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("pending", "Completed registration, but not in working status yet"),
                    ("working_below_threshold", "Координирует, минимум групп не набран (3)"),
                    ("working_ok", "Working, required amount of groups reached"),
                    ("working_limit_reached", "Координирует, максимум групп набран (10)"),
                    ("on_leave", "On leave"),
                    ("left_prematurely", "Announced that they cannot participate in the project"),
                    ("finished_stays", "Finished coordinating but remains in the project"),
                    ("finished_left", "Finished coordinating and left the project"),
                    ("removed", "All access revoked, accounts closed"),
                    ("banned", "Banned from the project"),
                ],
                help_text="Status of this coordinator with regard to project as a whole",
                max_length=50,
                verbose_name="Status in project",
            ),
        ),
        migrations.AlterField(
            model_name="speakingclub",
            name="teachers_under_18",
            field=models.ManyToManyField(
                blank=True, to="api.teacherunder18", verbose_name="teachers under 18"
            ),
        ),
    ]
