# Generated by Django 4.1.6 on 2023-02-11 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_teachercategory_teacherinfo_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinatorlogitem",
            name="from_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordinator_log_from_self",
                to="api.group",
            ),
        ),
        migrations.AlterField(
            model_name="coordinatorlogitem",
            name="to_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordinator_log_to_self",
                to="api.group",
            ),
        ),
        migrations.AlterField(
            model_name="studentlogitem",
            name="from_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_log_from_self",
                to="api.group",
            ),
        ),
        migrations.AlterField(
            model_name="studentlogitem",
            name="to_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_log_to_self",
                to="api.group",
            ),
        ),
        migrations.AlterField(
            model_name="teacherlogitem",
            name="from_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_log_from_self",
                to="api.group",
            ),
        ),
        migrations.AlterField(
            model_name="teacherlogitem",
            name="to_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_log_to_self",
                to="api.group",
            ),
        ),
    ]
