# Generated by Django 4.1.7 on 2023-03-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_dayandtimeslot_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouplogeventrule",
            name="log_event_type",
        ),
        migrations.RemoveField(
            model_name="studentlogeventrule",
            name="log_event_type",
        ),
        migrations.RemoveField(
            model_name="teacherlogeventrule",
            name="log_event_type",
        ),
        migrations.AlterField(
            model_name="dayandtimeslot",
            name="day_of_week_index",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                verbose_name="day of the week",
            ),
        ),
        migrations.DeleteModel(
            name="CoordinatorLogEventRule",
        ),
        migrations.DeleteModel(
            name="GroupLogEventRule",
        ),
        migrations.DeleteModel(
            name="StudentLogEventRule",
        ),
        migrations.DeleteModel(
            name="TeacherLogEventRule",
        ),
    ]
