# Generated by Django 4.1.6 on 2023-02-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_coordinatorlogitem_from_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminsiteuser",
            name="login",
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name="coordinatorinfo",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "This field has nothing to do with accessing Django admin site. "
                    "It marks coordinators that have special rights over ordinary coordinators."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="coordinatorlogitemname",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="coordinatorstatusname",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="dayofweek",
            name="name_en",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="dayofweek",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="dayofweek",
            name="name_ua",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="enrollmenttestquestion",
            name="text",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="enrollmenttestquestionoption",
            name="text",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="grouplogitemname",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="groupstatusname",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="informationsource",
            name="name_en",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="informationsource",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="informationsource",
            name="name_ua",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="languagelevel",
            name="name",
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="languagelevel",
            name="rank",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="nativelanguage",
            name="name_en",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="nativelanguage",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="nativelanguage",
            name="name_ua",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name="person",
            name="native_language",
        ),
        migrations.AlterField(
            model_name="studentlogitemname",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="studentstatusname",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="teachercategory",
            name="name_en",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="teachercategory",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="teachercategory",
            name="name_ua",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="teacherlogitemname",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="teacherstatusname",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="teachinglanguage",
            name="name_en",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="teachinglanguage",
            name="name_ru",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="teachinglanguage",
            name="name_ua",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="person",
            name="native_language",
            field=models.ManyToManyField(to="api.nativelanguage"),
        ),
    ]
