# Generated by Django 4.1.7 on 2023-03-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_remove_grouplogeventrule_log_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmenttestquestionoption",
            name="text",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="enrollmenttestquestionoption",
            constraint=models.UniqueConstraint(
                fields=("question_id", "text"), name="option_unique_per_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmenttestquestionoption",
            constraint=models.UniqueConstraint(
                fields=("question_id", "is_correct"), name="only_one_correct_option_per_question"
            ),
        ),
    ]
