# Generated by Django 4.1.7 on 2023-03-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_remove_personalinfo_comment_coordinator_comment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollmenttestresult",
            old_name="student_info",
            new_name="student",
        ),
        migrations.AddField(
            model_name="student",
            name="smalltalk_test_result",
            field=models.JSONField(
                blank=True, help_text="JSON received from SmallTalk API", null=True
            ),
        ),
    ]
