# Generated by Django 4.1.6 on 2023-02-11 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_adminsiteuser_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="coordinator_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.coordinatorinfo",
                verbose_name=(
                    "block of coordinator-specific information, if this person is a coordinator"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="information_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="api.informationsource",
                verbose_name="how did they learn about Samantha Smith's Group?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="student_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.studentinfo",
                verbose_name="block of student-specific information, if this person is a student",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="teacher_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.teacherinfo",
                verbose_name="block of teacher-specific information, if this person is a teacher",
            ),
        ),
    ]
