# Generated by Django 4.1.7 on 2023-03-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_rename_student_info_enrollmenttestresult_student_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentstatus",
            options={"verbose_name_plural": "possible student statuses (group studies)"},
        ),
        migrations.AlterModelOptions(
            name="teacherstatus",
            options={"verbose_name_plural": "possible teacher statuses (group studies)"},
        ),
        migrations.RenameField(
            model_name="student",
            old_name="status",
            new_name="group_status",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="status",
        ),
        migrations.AddField(
            model_name="teacher",
            name="group_status",
            field=models.ForeignKey(
                default=None,
                help_text="Status of the teacher with regard to group studies.",
                on_delete=django.db.models.deletion.PROTECT,
                to="api.teacherstatus",
            ),
            preserve_default=False,
        ),
    ]
