# Generated by Django 4.1.6 on 2023-02-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_person_coordinator_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinatorlogitemname",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="coordinatorstatusname",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="grouplogitemname",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="groupstatusname",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studentlogitemname",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studentstatusname",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="teacherlogitemname",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="teacherstatusname",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
