# Generated by Django 4.1.7 on 2023-03-07 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_enrollmenttestquestionoption_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="status_since",
        ),
    ]
