# Generated by Django 4.1.7 on 2023-03-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_remove_group_status_since"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="group_status",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="group_status",
        ),
        migrations.AddField(
            model_name="speakingclub",
            name="teachers_under_18",
            field=models.ManyToManyField(to="api.teacherunder18"),
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for a group"),
                    ("study", "Studying in a group"),
                    ("transfer", "Needs transfer to another group"),
                ],
                default="",
                help_text="status of this student with regard to group studies",
                max_length=10,
                verbose_name="group studies status",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for a group"),
                    ("teaching", "Teaching a group"),
                    ("transfer", "Needs transfer to another group"),
                ],
                default="",
                help_text="status of this teacher with regard to group studies",
                max_length=10,
                verbose_name="group studies status",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherunder18",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for a group"),
                    ("speak_club", "Teaching in a speaking club"),
                ],
                default="",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coordinator",
            name="status",
            field=models.CharField(
                choices=[("onboarding", "In onboarding"), ("working", "Working with a group")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("study", "Studying"), ("finish", "Finished")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="additional_skills_comment",
            field=models.CharField(
                blank=True,
                help_text="other ways in which the applicant could help, besides teaching or helping otherteachers with materials or feedback (comment)",
                max_length=255,
                null=True,
                verbose_name="comment on additional skills besides teaching",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="has_prior_teaching_experience",
            field=models.BooleanField(
                default=False,
                help_text="has the applicant already worked as a teacher before applying at Samantha Smith's Group?",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="simultaneous_groups",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="number of groups the teacher can teach simultaneously"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="student_age_ranges",
            field=models.ManyToManyField(
                help_text="age ranges of students that the teacher is willing to teach. The 'from's and 'to's of these ranges are wider than those the students choose for themselves.",
                to="api.agerange",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="weekly_frequency_per_group",
            field=models.PositiveSmallIntegerField(
                help_text="number of times per week the teacher can have classes with each group"
            ),
        ),
        migrations.AlterField(
            model_name="teacherunder18",
            name="additional_skills_comment",
            field=models.CharField(
                blank=True,
                help_text="other ways in which the applicant could help, besides teaching or helping otherteachers with materials or feedback (comment)",
                max_length=255,
                null=True,
                verbose_name="comment on additional skills besides teaching",
            ),
        ),
        migrations.DeleteModel(
            name="CoordinatorStatus",
        ),
        migrations.DeleteModel(
            name="GroupStatus",
        ),
        migrations.DeleteModel(
            name="StudentStatus",
        ),
        migrations.DeleteModel(
            name="TeacherStatus",
        ),
    ]
