# Generated by Django 4.1.7 on 2023-03-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_studentstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agerange",
            name="age_from",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="agerange",
            name="age_to",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="group",
            name="lesson_duration",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="languagelevel",
            name="rank",
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="group_status",
            field=models.ForeignKey(
                help_text="Status of this student with regard to group studies",
                on_delete=django.db.models.deletion.PROTECT,
                to="api.studentstatus",
                verbose_name="Group studies status",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="group_status",
            field=models.ForeignKey(
                help_text="Status of this teacher with regard to group studies.",
                on_delete=django.db.models.deletion.PROTECT,
                to="api.teacherstatus",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="simultaneous_groups",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Number of groups the teacher can teach simultaneously"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="weekly_frequency_per_group",
            field=models.PositiveSmallIntegerField(
                help_text="Number of times per week the teacher can have classes with each group"
            ),
        ),
    ]
