# Generated by Django 4.1.7 on 2023-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_agerange_age_from_alter_agerange_age_to_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="agerange",
            constraint=models.UniqueConstraint(fields=("age_from", "age_to"), name="age_from_to"),
        ),
        migrations.AddConstraint(
            model_name="communicationlanguagemode",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="fcommunicationlanguagemode_name_internal"
            ),
        ),
        migrations.AddConstraint(
            model_name="coordinatorlogeventname",
            constraint=models.UniqueConstraint(
                fields=("name",), name="fcoordinatorlogeventname_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="dayandtimeslot",
            constraint=models.UniqueConstraint(
                fields=("day_of_week", "time_slot"), name="day_and_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("telegram_chat_url",), name="telegram_chat_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="grouplogeventname",
            constraint=models.UniqueConstraint(fields=("name",), name="fgrouplogeventname_name"),
        ),
        migrations.AddConstraint(
            model_name="personalinfo",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "email"), name="full_name_and_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentlogeventname",
            constraint=models.UniqueConstraint(fields=("name",), name="fstudentlogeventname_name"),
        ),
        migrations.AddConstraint(
            model_name="teacherlogeventname",
            constraint=models.UniqueConstraint(fields=("name",), name="fteacherlogeventname_name"),
        ),
        migrations.AddConstraint(
            model_name="teachinglanguage",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="fteachinglanguage_name_internal"
            ),
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("from_utc_hour", "to_utc_hour"), name="from_to_hour"
            ),
        ),
    ]
