# Generated by Django 4.1.7 on 2023-03-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_remove_student_group_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakingclub",
            name="communication_language_mode",
            field=models.CharField(
                choices=[
                    ("ru", "Russian only"),
                    ("ua", "Ukrainian only"),
                    ("ru_ua", "Russian or Ukrainian"),
                    ("l2_only", "Only language being taught"),
                ],
                default="",
                max_length=10,
                verbose_name="Language(s) the students and teachers can speak in class",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="group",
            name="communication_language_mode",
            field=models.CharField(
                choices=[
                    ("ru", "Russian only"),
                    ("ua", "Ukrainian only"),
                    ("ru_ua", "Russian or Ukrainian"),
                    ("l2_only", "Only language being taught"),
                ],
                max_length=10,
                verbose_name="Language(s) the students and teachers can speak in class",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="communication_language_mode",
            field=models.CharField(
                choices=[
                    ("ru", "Russian only"),
                    ("ua", "Ukrainian only"),
                    ("ru_ua", "Russian or Ukrainian"),
                    ("l2_only", "Only language being taught"),
                ],
                max_length=10,
                verbose_name="Language(s) the students and teachers can speak in class",
            ),
        ),
        migrations.DeleteModel(
            name="CommunicationLanguageMode",
        ),
    ]
