# Generated by Django 4.1.7 on 2023-03-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_speakingclub_communication_language_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinator",
            name="status",
            field=models.CharField(
                choices=[("onboarding", "In onboarding"), ("working", "Working with a group")],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="coordinatorlogevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("joined", "Joined the team"),
                    ("onboard", "Started onboarding"),
                    ("onboard_end", "Finished onboarding"),
                    ("took_group", "Took a group"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="communication_language_mode",
            field=models.CharField(
                choices=[
                    ("ru", "Russian only"),
                    ("ua", "Ukrainian only"),
                    ("ru_ua", "Russian or Ukrainian"),
                    ("l2_only", "Only language being taught"),
                ],
                max_length=15,
                verbose_name="Language(s) the students and teachers can speak in class",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("study", "Studying"), ("finish", "Finished")],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="grouplogevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("formed", "Formed"),
                    ("confirmed", "Confirmed"),
                    ("started", "Started classes"),
                    ("finished", "Finished classes"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="communication_language_mode",
            field=models.CharField(
                choices=[
                    ("ru", "Russian only"),
                    ("ua", "Ukrainian only"),
                    ("ru_ua", "Russian or Ukrainian"),
                    ("l2_only", "Only language being taught"),
                ],
                max_length=15,
                verbose_name="Language(s) the students and teachers can speak in class",
            ),
        ),
        migrations.AlterField(
            model_name="speakingclub",
            name="communication_language_mode",
            field=models.CharField(
                choices=[
                    ("ru", "Russian only"),
                    ("ua", "Ukrainian only"),
                    ("ru_ua", "Russian or Ukrainian"),
                    ("l2_only", "Only language being taught"),
                ],
                max_length=15,
                verbose_name="Language(s) the students and teachers can speak in class",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for a group"),
                    ("study", "Studying in a group"),
                    ("transfer", "Needs transfer to another group"),
                ],
                help_text="status of this student with regard to group studies",
                max_length=15,
                verbose_name="group studies status",
            ),
        ),
        migrations.AlterField(
            model_name="studentlogevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("register", "Joined the team"),
                    ("start", "Started studying in a group"),
                    ("req_transf", "Requested transfer"),
                    ("transferred", "Transferred"),
                    ("missed_class", "Missed a class"),
                    ("finish_group", "Finished studying in a group"),
                    ("no_reply", "Not replying"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for a group"),
                    ("teaching", "Teaching a group"),
                    ("transfer", "Needs transfer to another group"),
                ],
                help_text="status of this teacher with regard to group studies",
                max_length=15,
                verbose_name="group studies status",
            ),
        ),
        migrations.AlterField(
            model_name="teacherlogevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("register", "Joined the team"),
                    ("start", "Started studying in a group"),
                    ("finish_group", "Finished studying in a group"),
                    ("no_reply", "Not replying"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="teacherunder18",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for a group"),
                    ("speak_club", "Teaching in a speaking club"),
                ],
                max_length=15,
            ),
        ),
        migrations.DeleteModel(
            name="CoordinatorLogEventType",
        ),
        migrations.DeleteModel(
            name="GroupLogEventType",
        ),
        migrations.DeleteModel(
            name="StudentLogEventType",
        ),
        migrations.DeleteModel(
            name="TeacherLogEventType",
        ),
    ]
