# Generated by Django 4.1.7 on 2023-03-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_coordinator_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name_internal",
                    models.CharField(
                        help_text="Internal name to use in code. This will allow to change user-facing names easily without breaking the code. Internal name must not change after adding it.",
                        max_length=50,
                        unique=True,
                        verbose_name="internal name",
                    ),
                ),
                (
                    "name_for_user",
                    models.CharField(max_length=100, verbose_name="Readable name for coordinator"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                fields=("name_internal",), name="flanguage_name_internal"
            ),
        ),
        migrations.AlterField(
            model_name="speakingclub",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.language"
            ),
        ),
        migrations.AlterField(
            model_name="teachinglanguageandlevel",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.language"
            ),
        ),
        migrations.DeleteModel(
            name="TeachingLanguage",
        ),
    ]
