# Generated by Django 5.1.7 on 2025-04-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_fake_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="project_status",
            field=models.CharField(
                choices=[
                    (
                        "needs_interview_to_determine_level",
                        "Requires oral interview to determine language levelbefore getting 'no_group_yet' status",
                    ),
                    ("no_group_yet", "Not studying, waiting for a group"),
                    ("study", "Studying in a group"),
                    ("on_leave", "On leave"),
                    ("left_prematurely", "Left the project prematurely"),
                    ("finished", "Completed the course and left the project"),
                    ("banned", "Banned from the project"),
                ],
                help_text="status of this student with regard to project as a whole",
                max_length=50,
                verbose_name="status in project",
            ),
        ),
        migrations.AlterField(
            model_name="teacherlogevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("registered", "Completed registration"),
                    (
                        "awaiting_offer",
                        "Registration and validation complete, started waiting for a group",
                    ),
                    ("group_offered", "Was offered a group, has not responded yet"),
                    ("accepted_offer", "Was offered a group and accepted it"),
                    ("validated", "Validated in a face-to-face interview"),
                    ("declined_offer", "Was offered a group but declined it"),
                    (
                        "tentative_group_discarded",
                        "Tentative group was discarded for reasons other than the person's own decision",
                    ),
                    ("group_confirmed", "Group confirmed, awaiting start of classes"),
                    ("started_teaching_group", "Started teaching a group"),
                    ("hosted_speaking_club", "Hosted a speaking club session"),
                    ("requested_transfer", "Requested transfer"),
                    ("transferred", "Transferred"),
                    ("transfer_canceled", "Transfer canceled"),
                    ("left_prematurely", "Left the project prematurely"),
                    (
                        "finished_and_leaving",
                        "Finished working and announced that they are leaving the project",
                    ),
                    (
                        "finished_and_staying",
                        "Finished working and announced that they are staying in the project",
                    ),
                    ("expelled", "Expelled from the project"),
                    ("access_revoked", "Access to corporate resources revoked"),
                    ("group_aborted", "Group finished prematurely"),
                    ("group_finished", "Group finished successfully"),
                    ("gone_on_leave", "Gone on leave"),
                    ("returned_from_leave", "Returned from leave"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="teacherunder18logevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("registered", "Completed registration"),
                    ("validated", "Validated in a face-to-face interview"),
                    ("hosted_speaking_club", "Hosted a speaking club session"),
                    ("left", "Left the project"),
                    ("expelled", "Expelled from the project"),
                    ("access_revoked", "Access to corporate resources revoked"),
                    ("gone_on_leave", "Gone on leave"),
                    ("returned_from_leave", "Returned from leave"),
                ],
                max_length=50,
            ),
        ),
    ]
