# Generated by Django 5.1.7 on 2025-04-23 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        db_index=True,
                        help_text="A unique identifier for the type of alert (e.g., 'overdue_on_leave', 'low_student_activity').",  # noqa: E501
                        max_length=100,
                        verbose_name="Alert Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(db_index=True, default=False, verbose_name="Is Resolved"),
                ),
                ("details", models.TextField(blank=True, verbose_name="Details")),
                ("object_id", models.PositiveIntegerField(verbose_name="Related Object ID")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Related Model Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="alert_content_object_idx"
                    ),
                    models.Index(
                        fields=["alert_type", "is_resolved"], name="alert_type_resolved_idx"
                    ),
                ],
            },
        ),
    ]
