# Generated by Django 5.1.7 on 2025-04-23 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "app_label": "api",
                    "model__in": ["coordinator", "group", "student", "teacher"],
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Related Model Type",
            ),
        ),
    ]
