# Generated by Django 5.2.10 on 2026-01-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alter_alert_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("overdue_on_leave", "Overdue on leave"),
                    ("overdue_transfer_request", "Overdue transfer request"),
                    ("coordinator_onboarding_stale", "Onboarding stale"),
                    ("low_student_activity", "Low student activity"),
                    ("teacher_no_group_45_days", "Teacher without group for 45 days"),
                    ("teacher_overdue_on_leave", "Teacher overdue on leave"),
                    ("teacher_overdue_group_offer", "Teacher overdue group offer"),
                    ("student_needs_oral_interview", "Student needs oral interview"),
                    ("student_overdue_group_offer", "Student overdue group offer"),
                    ("student_no_group_30_days", "Student without group for 30 days"),
                    ("group_pending_overdue", "Group pending overdue"),
                    ("group_awaiting_start_overdue", "Group awaiting start overdue"),
                ],
                db_index=True,
                help_text=(
                    "A unique identifier for the type of alert (e.g., 'overdue_on_leave', 'low_student_activity')."
                ),
                max_length=100,
                verbose_name="Alert Type",
            ),
        ),
    ]
