name: main

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    env:
      SECRET_KEY: "test-secret"
      DEBUG: "True"
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_HOST: 127.0.0.1
      DB_PORT: 5432

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --frozen

      - name: Wait for Postgres
        run: |
          until pg_isready -h 127.0.0.1 -p 5432; do sleep 1; done

      - name: Run tests
        run: |
          uv run pytest -v
