name: main

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Copy settings
        run: |
          cp ./django_webapps/settings_sample.py ./django_webapps/settings.py
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Copy settings
        run: |
          cp ./django_webapps/settings_sample.py ./django_webapps/settings.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --frozen
      - name: Run tests
        run: |
          uv run pytest -v
